// src/service/CustomerService.js
 const Agreementdata = {
    getCustomersLarge: () => {
        return Promise.resolve([
         {
        id: 1001,
        name: 'Ayesha Khan',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'Meezan Bank',
        date: '2024-07-10',
        status: 'active',
        verified: true,
        activity: 56,
        representative: { name: 'Ali Raza' },
        balance: 23000
    },
    {
        id: 1002,
        name: 'John Smith',
        country: { name: 'USA', code: 'US' },
        company: 'Bank of America',
        date: '2023-12-18',
        status: 'inactive',
        verified: false,
        activity: 22,
        representative: { name: 'Emily Carter' },
        balance: 15800
    },
    {
        id: 1003,
        name: 'Sara Ahmed',
        country: { name: 'Canada', code: 'CA' },
        company: 'RBC Bank',
        date: '2024-03-02',
        status: 'pending',
        verified: true,
        activity: 33,
        representative: { name: 'Michael Lee' },
        balance: 7400
    },
    {
        id: 1004,
        name: 'Omar Bashir',
        country: { name: 'UAE', code: 'AE' },
        company: 'Emirates NBD',
        date: '2024-01-25',
        status: 'active',
        verified: true,
        activity: 78,
        representative: { name: 'Noor Fatima' },
        balance: 52000
    },
    {
        id: 1005,
        name: 'Maria James',
        country: { name: 'UK', code: 'GB' },
        company: 'HSBC',
        date: '2024-05-14',
        status: 'qualified',
        verified: false,
        activity: 45,
        representative: { name: 'David Miller' },
        balance: 39000
    },
    {
        id: 1006,
        name: 'Bilal Arshad',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'HBL',
        date: '2024-06-19',
        status: 'inactive',
        verified: true,
        activity: 19,
        representative: { name: 'Zainab Shah' },
        balance: 18400
    },
    {
        id: 1007,
        name: 'Jessica Jones',
        country: { name: 'USA', code: 'US' },
        company: 'Chase Bank',
        date: '2023-11-07',
        status: 'active',
        verified: false,
        activity: 61,
        representative: { name: 'Chris Evans' },
        balance: 62000
    },
    {
        id: 1008,
        name: 'Ahmad Raza',
        country: { name: 'UK', code: 'GB' },
        company: 'Barclays',
        date: '2024-04-03',
        status: 'qualified',
        verified: true,
        activity: 29,
        representative: { name: 'Sana Malik' },
        balance: 30500
    },
    {
        id: 1009,
        name: 'Emily Watson',
        country: { name: 'Canada', code: 'CA' },
        company: 'Scotiabank',
        date: '2024-02-11',
        status: 'unqualified',
        verified: false,
        activity: 14,
        representative: { name: 'Daniel Green' },
        balance: 9900
    },
    {
        id: 1010,
        name: 'Rizwan Ali',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'UBL',
        date: '2024-07-01',
        status: 'active',
        verified: true,
        activity: 83,
        representative: { name: 'Fatima Zahra' },
        balance: 44000
    },
     {
        id: 1001,
        name: 'Ayesha Khan',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'Meezan Bank',
        date: '2024-07-10',
        status: 'active',
        verified: true,
        activity: 56,
        representative: { name: 'Ali Raza' },
        balance: 23000
    },
    {
        id: 1002,
        name: 'John Smith',
        country: { name: 'USA', code: 'US' },
        company: 'Bank of America',
        date: '2023-12-18',
        status: 'inactive',
        verified: false,
        activity: 22,
        representative: { name: 'Emily Carter' },
        balance: 15800
    },
    {
        id: 1003,
        name: 'Sara Ahmed',
        country: { name: 'Canada', code: 'CA' },
        company: 'RBC Bank',
        date: '2024-03-02',
        status: 'pending',
        verified: true,
        activity: 33,
        representative: { name: 'Michael Lee' },
        balance: 7400
    },
    {
        id: 1004,
        name: 'Omar Bashir',
        country: { name: 'UAE', code: 'AE' },
        company: 'Emirates NBD',
        date: '2024-01-25',
        status: 'active',
        verified: true,
        activity: 78,
        representative: { name: 'Noor Fatima' },
        balance: 52000
    },
    {
        id: 1005,
        name: 'Maria James',
        country: { name: 'UK', code: 'GB' },
        company: 'HSBC',
        date: '2024-05-14',
        status: 'qualified',
        verified: false,
        activity: 45,
        representative: { name: 'David Miller' },
        balance: 39000
    },
    {
        id: 1006,
        name: 'Bilal Arshad',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'HBL',
        date: '2024-06-19',
        status: 'inactive',
        verified: true,
        activity: 19,
        representative: { name: 'Zainab Shah' },
        balance: 18400
    },
    {
        id: 1007,
        name: 'Jessica Jones',
        country: { name: 'USA', code: 'US' },
        company: 'Chase Bank',
        date: '2023-11-07',
        status: 'active',
        verified: false,
        activity: 61,
        representative: { name: 'Chris Evans' },
        balance: 62000
    },
    {
        id: 1008,
        name: 'Ahmad Raza',
        country: { name: 'UK', code: 'GB' },
        company: 'Barclays',
        date: '2024-04-03',
        status: 'qualified',
        verified: true,
        activity: 29,
        representative: { name: 'Sana Malik' },
        balance: 30500
    },
    {
        id: 1009,
        name: 'Emily Watson',
        country: { name: 'Canada', code: 'CA' },
        company: 'Scotiabank',
        date: '2024-02-11',
        status: 'unqualified',
        verified: false,
        activity: 14,
        representative: { name: 'Daniel Green' },
        balance: 9900
    },
    {
        id: 1010,
        name: 'Rizwan Ali',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'UBL',
        date: '2024-07-01',
        status: 'active',
        verified: true,
        activity: 83,
        representative: { name: 'Fatima Zahra' },
        balance: 44000
    },
     {
        id: 1001,
        name: 'Ayesha Khan',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'Meezan Bank',
        date: '2024-07-10',
        status: 'active',
        verified: true,
        activity: 56,
        representative: { name: 'Ali Raza' },
        balance: 23000
    },
    {
        id: 1002,
        name: 'John Smith',
        country: { name: 'USA', code: 'US' },
        company: 'Bank of America',
        date: '2023-12-18',
        status: 'inactive',
        verified: false,
        activity: 22,
        representative: { name: 'Emily Carter' },
        balance: 15800
    },
    {
        id: 1003,
        name: 'Sara Ahmed',
        country: { name: 'Canada', code: 'CA' },
        company: 'RBC Bank',
        date: '2024-03-02',
        status: 'pending',
        verified: true,
        activity: 33,
        representative: { name: 'Michael Lee' },
        balance: 7400
    },
    {
        id: 1004,
        name: 'Omar Bashir',
        country: { name: 'UAE', code: 'AE' },
        company: 'Emirates NBD',
        date: '2024-01-25',
        status: 'active',
        verified: true,
        activity: 78,
        representative: { name: 'Noor Fatima' },
        balance: 52000
    },
    {
        id: 1005,
        name: 'Maria James',
        country: { name: 'UK', code: 'GB' },
        company: 'HSBC',
        date: '2024-05-14',
        status: 'qualified',
        verified: false,
        activity: 45,
        representative: { name: 'David Miller' },
        balance: 39000
    },
    {
        id: 1006,
        name: 'Bilal Arshad',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'HBL',
        date: '2024-06-19',
        status: 'inactive',
        verified: true,
        activity: 19,
        representative: { name: 'Zainab Shah' },
        balance: 18400
    },
    {
        id: 1007,
        name: 'Jessica Jones',
        country: { name: 'USA', code: 'US' },
        company: 'Chase Bank',
        date: '2023-11-07',
        status: 'active',
        verified: false,
        activity: 61,
        representative: { name: 'Chris Evans' },
        balance: 62000
    },
    {
        id: 1008,
        name: 'Ahmad Raza',
        country: { name: 'UK', code: 'GB' },
        company: 'Barclays',
        date: '2024-04-03',
        status: 'qualified',
        verified: true,
        activity: 29,
        representative: { name: 'Sana Malik' },
        balance: 30500
    },
    {
        id: 1009,
        name: 'Emily Watson',
        country: { name: 'Canada', code: 'CA' },
        company: 'Scotiabank',
        date: '2024-02-11',
        status: 'unqualified',
        verified: false,
        activity: 14,
        representative: { name: 'Daniel Green' },
        balance: 9900
    },
    {
        id: 1010,
        name: 'Rizwan Ali',
        country: { name: 'Pakistan', code: 'PK' },
        company: 'UBL',
        date: '2024-07-01',
        status: 'active',
        verified: true,
        activity: 83,
        representative: { name: 'Fatima Zahra' },
        balance: 44000
    }
            // Add more records as needed
        ]);
    }
};
export default  Agreementdata;